import fixture from './seed.json';
import type { api as originalApi } from '../lib/api/client';
import type { AppError, ProjectDetail, Artifact, CodexConversationResponse, DeploymentAuthorization, Deployment, Task } from '../lib/api/types';
const clone=<T,>(v:T):T=>structuredClone(v);
export const DEMO_PROJECT_ID=fixture.project.id;
const STORE='point-line-plane:original-ui-demo:v2',now=()=>new Date().toISOString(),future=()=>new Date(Date.now()+86400000).toISOString();
const delay=(ms=250)=>new Promise<void>(resolve=>setTimeout(resolve,ms));
export function isAppError(v:unknown):v is AppError{return !!v&&typeof v==='object'&&'userMessage'in v;}
function fresh(){return {project:clone(fixture.project) as ProjectDetail,artifacts:clone(fixture.artifacts) as Artifact[],conversations:[clone(fixture.conversation)] as any[],activeConversation:'demo-idea',deployments:clone(fixture.deployments),authorization:null as DeploymentAuthorization|null,task:null as Task|null,taskStarted:0,deleted:false,style:'obscura-pixel'};}
let state=fresh();try{const raw=localStorage.getItem(STORE);if(raw){const saved=JSON.parse(raw);if(saved.project?.id===DEMO_PROJECT_ID&&Array.isArray(saved.artifacts)&&saved.conversations?.length)state={...state,...saved};}}catch{}
function save(){try{localStorage.setItem(STORE,JSON.stringify(state));}catch{}}
function seedUI(){try{const id=DEMO_PROJECT_ID;if(!localStorage.getItem(`deployment-conversations:${id}`))localStorage.setItem(`deployment-conversations:${id}`,JSON.stringify({activeId:fixture.guide.id,items:[fixture.guide]}));localStorage.setItem(`deployment-entry-policy:${id}`,'2');if(!localStorage.getItem(`product-factory-ui-style:${id}`))localStorage.setItem(`product-factory-ui-style:${id}`,'obscura-pixel');}catch{}}
seedUI();
export function resetDemo(){state=fresh();try{for(const k of [STORE,`deployment-conversations:${DEMO_PROJECT_ID}`,`product-factory-ui-style:${DEMO_PROJECT_ID}`,'point-line-plane:demo:lemon:v1'])localStorage.removeItem(k);}catch{}seedUI();save();const u=new URL(location.href);u.search='';location.replace(u.href);}
function project(){state.project.latest_artifacts=state.artifacts;return clone(state.project);}
function conversation():CodexConversationResponse{const c=state.conversations.find(c=>c.conversation_id===state.activeConversation)??state.conversations[0];return {...clone(c),project:project()};}
function authorization():DeploymentAuthorization{return {id:'demo-authorization',project_id:DEMO_PROJECT_ID,credential_ref_id:'demo-cloud',action:'deploy',provider:'volcano_engine',region:'cn-beijing',environment:'production',permission_scope:{operations:['发布网页','检查访问','保留案例记录']},estimated_cost:{pricing_configured:true,amount_minor:0,currency:'CNY',note:'Demo 模拟操作，不创建云资源、不扣费',resource_plan:{gateway:'柠檬 Demo 入口',gateway_action:'reuse_bound_gateway',compute:'内置演示环境'}},status:'pending',expires_at:future(),created_at:now()};}
const credential={id:'demo-cloud',project_id:DEMO_PROJECT_ID,provider:'volcano_engine',service:'vefaas',scope:'project',masked_access_key:'DEMO · 内置案例',status:'verified',expires_at:null,created_at:fixture.project.created_at};
function taskProgress(){if(state.task?.status==='running'){state.task.progress=Math.min(100,Math.round((Date.now()-state.taskStarted)/24));if(state.task.progress===100){state.task.status='succeeded';state.project.stage=state.task.checkpoint.production_preparation?'DEPLOYMENT':'PREVIEW_REVIEW';state.project.preview_accepted=!!state.task.checkpoint.production_preparation;state.project.production_prepared=!!state.task.checkpoint.production_preparation;state.project.preview=clone(fixture.project.preview);state.project.preview_token='lemon-demo-preview';}state.project.active_task=clone(state.task);save();}return clone(state.task??state.project.active_task!);}
function startTask(production=false){state.taskStarted=Date.now();state.task={...clone(fixture.project.active_task),id:'demo-task-'+Date.now(),status:'running',progress:10,checkpoint:{ui_style_key:state.style,last_completed_step:'generating',production_preparation:production}};state.project.active_task=clone(state.task);state.project.stage=production?'DEPLOYMENT':'DEVELOPMENT';save();return clone(state.task);}
function finishDeploy(){const base=clone(fixture.deployments[0]);const dep={...base,id:'demo-release-'+Date.now(),revision:Math.max(...state.deployments.map(d=>d.revision))+1,created_at:now(),updated_at:now()};state.deployments.unshift(dep);if(state.authorization)state.authorization.status='consumed';save();return clone(dep);}
function reply(message:string,stage='idea'){
 if(/费用|花钱|收费|购买/.test(message))return '这是柠檬项目的内置 Demo。检查、生成和发布都在浏览器里模拟，不会购买资源，也不会扣除 AI 额度。';
 if(/数据|保存|登录/.test(message))return '柠檬案例采用浏览器本地保存：无需登录，专注时长和当日完成次数保存在当前浏览器。可以刷新预览，检查计时状态是否恢复。';
 if(/修改|调整/.test(message))return '已记录本次演示修改意见。你可以继续查看柠檬的需求、方案和可交互预览；Demo 会演示确认和生成流程，产物仍采用内置的柠檬案例。';
 if(/测试|验收|试用/.test(message))return '打开柠檬预览，体验设置时长、开始、暂停、继续和提前结束。自然完成的专注才计入次数；点击“演示到时”，可快速查看完成后手动开始休息的流程。';
 return stage==='idea'?'柠檬的核心目标是个人学习专注。内置案例包含自定义时长、暂停继续、完成提醒和当日次数。可查看右侧完整 PRD，或继续确认方案。':'已按柠檬案例完成本次模拟检查。可在右侧七步导航查看上线准备、方案费用、操作权限、线上版本、发布、验收和使用说明。';
}
const methods:Record<string,(...args:any[])=>any>={
 health:async()=>({status:'ok',mode:'static-demo'}),capabilities:async()=>({ai_provider_mode:'mock',ai_provider:'demo',ai_model:'案例回放',generated_execution_mode:'browser_demo',deployment_enabled:true,deployment_mode:'external',deployment_provider:'volcano_engine',deployment_region:'cn-beijing',github_sync_mode:'mock'}),
 me:async()=>({user:{id:'demo-visitor',display_name:'体验用户',quota:{},created_at:fixture.project.created_at}}),startCodexLogin:async()=>({attempt_id:'demo',status:'authenticated',auth_url:null,account:{email:'',plan_type:'demo',display_name:'体验用户'},error:null}),codexLoginStatus:async()=>methods.startCodexLogin(),login:async()=>methods.me(),demoLogin:async()=>methods.me(),logout:async()=>({ok:true}),
 projects:async()=>({items:state.deleted?[]:[project()]}),project:async()=>{taskProgress();return project();},createProject:async()=>{state.deleted=false;save();return project();},deleteProject:async()=>{state.deleted=true;save();return {ok:true};},
 artifacts:async()=>({items:clone(state.artifacts)}),codexConversation:async()=>conversation(),codexConversations:async()=>({items:state.conversations.map(c=>({id:c.conversation_id,title:c.title,active:c.conversation_id===state.activeConversation,message_count:c.messages.length,created_at:fixture.project.created_at,updated_at:now()}))}),
 createCodexConversation:async()=>{const c={...clone(fixture.conversation),conversation_id:'demo-conversation-'+Date.now(),title:'新的柠檬案例对话',messages:[{id:'welcome',role:'assistant',content:'这是柠檬项目演示。试着说“做一个柠檬番茄闹钟”，体验从点子到 PRD 的流程。'}],draft:null,current_question:null};state.project.stage='PRD_REVIEW';state.conversations.unshift(c);state.activeConversation=c.conversation_id;save();return conversation();},activateCodexConversation:async(_p:string,id:string)=>{state.project.stage='PRD_REVIEW';state.activeConversation=id;save();return conversation();},
 sendCodexMessage:async(_p:string,message:string,signal?:AbortSignal,onReasoning?:(s:string)=>void,_prefs?:unknown,onReply?:(s:string)=>void)=>{state.project.stage='PRD_REVIEW';const c=state.conversations.find(c=>c.conversation_id===state.activeConversation)!;const count=c.messages.filter((m:any)=>m.role==='user').length;onReasoning?.('正在读取内置柠檬案例，模拟整理需求');await delay(700);if(signal?.aborted)throw new DOMException('Aborted','AbortError');let text=reply(message),status='reply';if(!c.draft&&count===0){text='先确认这款柠檬闹钟的主要使用场景。';c.current_question={mode:'single',prompt:'主要用于什么场景？',options:['个人学习专注','工作专注','日常提醒']};status='question';}else if(!c.draft&&count===1){text='已明确使用场景。首版最重要的功能是什么？';c.current_question={mode:'multiple',prompt:'选择首版核心功能',options:['可自定义专注与休息时长','暂停与继续','当日次数记录']};status='question';}else if(!c.draft||/生成|PRD|需求文档/i.test(message)){c.draft=clone(fixture.conversation.draft);c.current_question=null;text='已载入柠檬项目的完整 PRD。请检查右侧内容，再确认进入方案。';status='prd_ready';}c.messages.push({id:crypto.randomUUID(),role:'user',content:message},{id:crypto.randomUUID(),role:'assistant',content:text});c.title='柠檬番茄闹钟';onReply?.(text);save();return {...clone(c),project:project(),status,reply:text,artifact:clone(state.artifacts.find(a=>a.type==='prd'))};},
 answerRequirement:async(_p:string,m:string)=>({project:project(),status:'reply',reply:reply(m)}),uploadRequirement:async(_p:string,file:File)=>({project:project(),status:'reply',reply:`已模拟接收“${file.name}”。文件不会上传，继续使用内置柠檬案例。`}),
 confirmArtifact:async(_p:string,type:string,id:string,decision:string,comment?:string)=>{await delay(600);const a=state.artifacts.find(a=>a.id===id)??state.artifacts.find(a=>a.type===type)!;a.status=decision==='confirm'?'confirmed':'draft';if(comment)a.content.revision_notes=[...(a.content.revision_notes as string[]??[]),`Demo 修改意见：${comment}`];state.project.stage=type==='prd'?'SOLUTION_REVIEW':decision==='confirm'?'DEVELOPMENT':'SOLUTION_REVIEW';if(type==='prd'){const c=state.conversations.find(c=>c.conversation_id===state.activeConversation);if(c)c.draft=clone(a.content);}if(type==='solution'&&decision==='confirm'){state.project.active_task=null;state.project.preview=null;state.project.preview_token=null;state.project.production_prepared=false;}save();return {project:project(),artifact:clone(a),next_artifact:clone(state.artifacts.find(a=>a.type==='solution'))};},
 quoteProjectCost:async()=>({id:'demo-cost',project_id:DEMO_PROJECT_ID,requires_confirmation:false,status:'confirmed',estimated_cost_microusd:0,pricing_configured:true,expires_at:future()}),confirmCostAuthorization:async()=>methods.quoteProjectCost(),
 startDevelopment:async(_p:string,style:string)=>{state.style=style;return startTask();},task:async()=>taskProgress(),retryTask:async()=>startTask(),developmentRuns:async()=>({items:[{...clone(fixture.runs[0]),context:{product_context:{ui_style_key:state.style}}}]}),workspace:async()=>({id:'demo-workspace',project_id:DEMO_PROJECT_ID,runtime_type:'browser',status:'ready',current_commit_ref:'lemon-demo',file_count:2,size_bytes:16000,created_at:now(),updated_at:now()}),qualityHistory:async()=>({quality_runs:[],repair_attempts:[]}),
 preview:async()=>({...clone(fixture.preview),url_path:`./lemon/?theme=${state.style==='obscura-pixel'?'obscura-pixel':'fresh'}`,code_version:{...clone(fixture.preview.code_version),commit_ref:'demo-'+state.style}}),acceptPreview:async()=>{state.project.preview_accepted=true;save();return {decision:'accepted'};},prepareProduction:async()=>{await delay(800);state.project.production_prepared=true;state.project.stage='DEPLOYMENT';state.project.active_task={...clone(fixture.project.active_task),checkpoint:{production_preparation:true,ui_style_key:state.style}};save();return clone(state.project.active_task);},previewFeedback:async(_p:string,f:string)=>({classification:'demo',reason:reply(f),next_stage:'PREVIEW_REVIEW',project:project()}),
 cloudCredentials:async()=>({items:[clone(credential)]}),connectCloudCredential:async()=>{await delay(450);return clone(credential);},verifyCloudCredential:async()=>{await delay(300);return clone(credential);},productionReadiness:async()=>clone(fixture.readiness),selectLightweightDeployment:async()=>clone(fixture.readiness),connectDeploymentDatabase:async()=>clone(fixture.readiness),deploymentAuthorizations:async()=>({items:state.authorization?[clone(state.authorization)]:[]}),quoteDeployment:async()=>{await delay(450);state.authorization=authorization();save();return clone(state.authorization);},confirmDeployment:async()=>{state.authorization??=authorization();state.authorization.status='confirmed';save();return clone(state.authorization);},startDeployment:async()=>{await delay(1100);return finishDeploy();},deployments:async()=>({items:clone(state.deployments)}),
 deploymentAgentMessage:async(_p:string,id:string,message:string,signal?:AbortSignal)=>{await delay(650);if(signal?.aborted)throw new DOMException('Aborted','AbortError');let selected_step_id='inspect',action='explain',text=reply(message,'launch');if(/费用|方案/.test(message)){selected_step_id='permissions';action='quote_deployment';state.authorization=authorization();}else if(/权限|授权/.test(message)){selected_step_id='operation_review';}else if(/准备.*版本|配置/.test(message)){selected_step_id='online_code';}else if(/发布|部署|上线/.test(message)){selected_step_id='backend';action='show_deployment_result';text='已读取内置柠檬发布记录。这里使用模拟发布结果，可继续检查使用效果和领取演示网址。';}else if(/网址|完成|说明/.test(message)){selected_step_id='acceptance';action='show_deployment_result';}else if(/验收|效果|试用/.test(message)){selected_step_id='address';action='open_preview';}save();return {project:project(),conversation_id:id,thread_id:'demo',turn_id:crypto.randomUUID(),reply:text,status:'guidance',action,selected_step_id,skill:{name:'vibe-deployment',source:'内置案例',mode:'real_guarded'},authorization:clone(state.authorization),deployment:clone(state.deployments[0]) as Deployment};},
 uploadDeploymentAttachment:async(_p:string,file:File)=>({filename:file.name,content_type:file.type,size_bytes:file.size,extracted_characters:0,stored:false,reply:'已模拟接收附件。文件留在当前浏览器，不会上传。'}),usageSummary:async()=>({total_tokens:0,total_cost_microusd:0,items:[]}),usageLedger:async()=>({items:[]}),quota:async()=>({plan:'demo',granted_units:0,consumed_units:0,reserved_units:0}),modelCredentials:async()=>({items:[]}),downloadUrl:()=> './lemon/',
};
export const api=new Proxy({baseUrl:''},{get(_target,name){if(name==='baseUrl')return '';return methods[String(name)]??(async()=>{throw {code:'DEMO_ONLY',message:'Demo',userMessage:'此操作在 Demo 中不连接外部服务。请通过柠檬案例继续体验四步流程。',status:400,retryable:false};});}}) as typeof originalApi;
